#!/bin/sh

# Check which waybar theme is set
THEMEIS=$(readlink -f ~/.config/waybar/style.css | cut -d '-' -f2)

#if the theme is not dark then we need to switch to it
if [ $THEMEIS != "bw.css" ]; then
    SWITCHTO="-bw"
fi

#set the waybar theme
ln -sf ~/.config/waybar/style/style$SWITCHTO.css ~/.config/waybar/style.css

#set the wofi theme
ln -sf ~/.config/wofi/style/style$SWITCHTO.css ~/.config/wofi/style.css

#set the xfce theme
xfconf-query -c xsettings -p /Net/ThemeName -s "theme$SWITCHTO"
xfconf-query -c xsettings -p /Net/IconThemeName -s "icons$SWITCHTO"

#set the GTK theme
gsettings set org.gnome.desktop.interface gtk-theme "theme$SWITCHTO"
gsettings set org.gnome.desktop.interface icon-theme "icons$SWITCHTO"

#change the background image and be cool about it ;)
swww img ~/.config/hypr/wallpapers/wallpaper$SWITCHTO.jpg --transition-fps 60 --transition-type wipe --transition-duration 2

#update the sddm image
ln -sf /usr/share/sddm/themes/sdt/Backgrounds/wallpaper$SWITCHTO.jpg /usr/share/sddm/themes/sdt/wallpaper.jpg

#restart the waybar
killall -SIGUSR2 waybar